<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
		"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
	<title>Joint Effect of Multiple Genetic Variations</title>

	<link rel="stylesheet" type="text/css" href="./style.css">
	<!--<link rel="stylesheet" type="text/css" href="./jquery-ui-1.11.2/jquery-ui.css">
	<link rel="stylesheet" type="text/css" href="./autocomplete.css">

	<script type="text/javascript" src="./jquery-ui-1.11.2/external/jquery/jquery.js"></script>
	<script type="text/javascript" src="./jquery-ui-1.11.2/jquery-ui.min.js"></script>
	<script type="text/javascript" src="./autocompleteIndividualId.js"></script>-->

</head>
<body>
	<div id="top"><h1>&nbsp;Joint Effect of Multiple Genetic Variations</h1></div>
	<div id="menu">
		<h1>
			<a href="http://bioinformatics.cs.vt.edu/~treiter/index.php">Home</a>
		</h1>
		<h1>
			<a href="http://bioinformatics.cs.vt.edu/~treiter/download.php">Downloads</a>
		</h1>
		<h1>
			<a href="http://bioinformatics.cs.vt.edu/~treiter/search.php">Search</a>
		</h1>
	</div>

	<div id="content">

